<?= $this->doctype() ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?= $this->headTitle('Zend Translate')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
			 ->appendName('viewport', 'width=device-width, initial-scale=1.0')
			 ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?= $this->headLink([
		'rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
		'href' => $this->basePath() . '/img/favicon.ico'
	])
			 ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
			 ->prependStylesheet($this->basePath('css/style.css'))
	?>

	<!-- Scripts -->
	<?= $this->headScript()
			 ->prependFile($this->basePath('js/bootstrap.min.js'))
			 ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
	?>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
	<div class="container">
		<a class="navbar-brand" href="<?= $this->url('home') ?>">
			<img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>" />&nbsp; Zend Translate
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="<?= $this->url('home') ?>">Anasayfa <span class="sr-only">(current)</span></a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container">
	<?= $this->content ?>
	<hr>
	<footer>
		<p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
	</footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
