<section class="mt-5 mb-5">
	<form action="<?php echo $this->url('home') ?>" method="post">
		<div class="row">
			<div class="col">
				<div class="form-group">
					<label for="from">From</label> <select id="from" class="form-control" name="from">
						<option value="detect">Detect language</option>
						<?php foreach ($languages as $language) { ?>
							<option value="<?php echo $language['language']; ?>" <?php echo $language['language'] == $source ? 'selected' : null; ?>>
								<?php echo $language['name']; ?>
							</option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group">
					<label for="words">Words</label>
					<input class="form-control" id="words" name="words" rows="3" value="<?php echo $words; ?>">
				</div>
				<div class="form-group">
					<label for="text">Text</label>
					<textarea class="form-control" id="text" name="text" rows="3"><?php echo $text; ?></textarea>
				</div>
			</div>
			<div class="col">
				<div class="form-group">
					<label for="target">To</label> <select id="target" class="form-control" name="target">
						<?php foreach ($languages as $language) { ?>
							<option value="<?php echo $language['language']; ?>" <?php echo $language['language'] == $target ? 'selected' : null; ?>>
								<?php echo $language['name']; ?>
							</option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group">
					<label for="result">Result</label>
					<ul class="list-group" id="result">
						<?php foreach ($translations as $translation) { ?>
							<li class="list-group-item">
								<?php echo \Application\View\Helper\Highlight::make($words, $translation['translatedText']); ?>
							</li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="float-right">
					<button type="submit" class="btn btn-outline-primary">Translate</button>
				</div>
			</div>
		</div>
	</form>
</section>